### ISSUE TITLE
SEGSEGV with recent kernel and seccomp

### ISSUE THREAD

**Issue by alkino** [proot-me/proot#106]
When I use proot with a recent kernel (4.8.4 and above) I got a segv.
When I disable SECCOMP with PROOT_NO_SECCOMP=1 it works.

I dig a little but I don't know seccomp at all.

**Comment by alkino** [comment]
Has been fixed by: https://github.com/openmole/PRoot/commit/10119a1f1fd7dea012464ae176c2b5fc3eb18928
@vincenthage: can we have some explanations on your investigations?

**Comment by jopasserat** [comment]
We did a bit of digging to find it with @romainreuillon but the manpage helped:

> If  fork(2)  or clone(2) is allowed by the filter, any child processes will be constrained to the same system call filters as the parent.  If execve(2) is allowed, the existing filters will be preserved across a call to execve(2).

This seems to work as filters that can't be unset when set. Setting one to 0 disables the filter and enables children processes to actually capture the event.

We're not experts in low-level stuff unfortunately so don't take our word for granted.

Our fork was mainly to integrate the work @vincenthage did over the summer to provide Docker-like networking extensions in CARE archives used in @OpenMOLE.

Would be great to team up on maintaining / pushing PRoot / CARE further if @cedric-vincent is not able to do it anymore. What do you think @alkino?

**Comment by alkino** [comment]
I think we can fork it, yeah. Any advice @ivoire or @cedric-vincent?

**Comment by cedric-vincent** [comment]
@alkino, @jopasserat, @vincenthage, you should have received an invitation to be owner of the "proot-me" organisation on Github.  Feel free to maintain PRoot (and/or your work related to) here, if you wish.

I would be glad if you maintain this project,
Cédric.

**Comment by cedric-vincent** [comment]
Regarding this issue, maybe this could help:

> We support Linux 4.8 kernels. This was a significant amount of work because in 4.8,
> PTRACE_SYSCALL notifications moved to being delivered before seccomp notifications
> instead of afterward. (It's a good change, though, because as well as fixing a security hole,
> it also improves rr recording performance; the number of ptrace notifications for each
> ptrace-recorded syscall decreases from 3 to 2.) This also uncovered a serious (to rr)
> kernel bug with missing PTRACE_EVENT_EXIT notifications, which fortunately we were
> able to get fixed upstream (thanks to Kees Cook).

-- http://robert.ocallahan.org/2016/10/rr-440-released.html

**Comment by cedric-vincent** [comment]
I also sent an invitation to @meefik.

**Comment by alkino** [comment]
Thank you @cedric-vincent for your trust.

**Comment by jopasserat** [comment]
Thanks for everything around PRoot @cedric-vincent and for trusting us.

Would you have any document that could be useful for us? Usage stats? Users/devs we could get in touch with?

**Comment by Gnurou** [comment]
Just wanted to say thanks a lot for the PROOT_NO_SECCOMP=1 hint. I have been wondering why proot suddently stopped working for the last hour!

Looking forward to seeing further releases under the new maintainership!

**Comment by jopasserat** [comment]
Glad it helped @Gnurou. Please note though that early performance tests we've been running suggest a significant performance drop when disabling Seccomp (something like 4 times as slow on a IO heavy application).

So we need to find an actual solution to re-enable seccomp in the future. #helpwanted ;)

**Comment by IceflowRE** [comment]
I tried the proot from openmole but got: 

```
$ sudo proot -R . -q qemu-arm-static
-sh: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
```

**Comment by jopasserat** [comment]
I haven't tested the qemu mode yet so it could be linked.
Do you have the same issue without the `-q` flag?

Also, this kind of issues might be better to report on the mailing list until they're proved to be actual bugs / missing features from the project.

**Comment by IceflowRE** [comment]
Same issue without the -q flag.
Where to find the mailing list?

**Comment by jopasserat** [comment]
https://proot-me.github.io/#support

**Comment by jorge-lip** [comment]
Hi. any news regarding #106 and the SECCOMP problem ?
Besides 4.8 kernels, I see that in CentOS 6 the accelerated mode 2 does not work and proot uses mode 1.
Without the filtering it gets really slow on all applications that use syscalls intensively,

**Comment by alkino** [comment]
I'm on it. Really near now I think.
Problems comes from reordering like @cedric-vincent said.

**Comment by jopasserat** [comment]
May I ask what track you're following @alkino? We've hit so many walls trying to fix that with @romainreuillon we'd be glad to understand what was the root of the problem :)

**Comment by jorge-lip** [comment]
Hi, After posting the question, I decided to look at it over the weekend and I come out with this dirty solution changing tracee/event.c which seems to work ok. Maybe can help you guys to find a cleaner solution.

I'm using proot for udocker (https://github.com/indigo-dc/udocker) a tool to run docker containers without privileges.

**Comment by jorge-lip** [comment]
Hi, After posting the question, I decided to look at it over the weekend and I come out with this dirty solution changing tracee/event.c which seems to work ok. Maybe can help you to find a better solution.

https://owncloud.indigo-datacloud.eu/index.php/s/yMj5yd24zY5kXIJ

I'm using proot for udocker (https://github.com/indigo-dc/udocker) a tool to run docker containers without privileges.

**Comment by alkino** [comment]
Could you do a PR, please?

**Comment by jorge-lip** [comment]
Done, fix event.c for seccomp and ptrace #115

**Comment by alkino** [comment]
First, thanks for that @jorge-lip 

But a fall trough from `SIGTRAP` to `PTRACE_SECCOMP` seems me really weird.
Can you explain what you understand of the problem and why you fix it like that?

**Comment by mirage335** [comment]
With this "fix", I still need to use "export PROOT_NO_SECCOMP=1", and further, proot does not work at all with a PREEMPT_RT kernel.

**Comment by necrophcodr** [comment]
This issue is still present on the recent versions of proot, and have been reproduced on Sabayon 17.04 Xfce AMD64.

**Comment by mirage335** [comment]
Redirection of folders visible to applications with hardcoded expectations (eg. Arduino, emacs, FireFox, Slic3r, Cura, Pronterface, etc), is an essential feature for ensuring these applications can be configured for a specific purpose (eg. https://github.com/mirage335/MarlinBuilder/blob/master/launchArduino) .

PRoot's methods and syntax present the logical solution to this problem, yet, it has not been acceptably reliable for production use, if for no other reason than **this bug report has been allowed to remain open for more than a year**.

Ubiquitous Bash is significantly inspired as a workaround to this bug report, and after approximately four months intensive development, is now operational on Linux systems, especially Debian Stretch. Application virtualization, with file parameter translation and permission dropping, is supported. Several virtualization backends are available to chose from, including ChRoot, QEMU, VirtualBox, and Docker, all working with the same raw VM image. If for any reason one of these backends is unsuitable or unavailable, an alternative can be launched within seconds.

https://rawgit.com/mirage335/ubiquitous_bash/master/USAGE.html
https:/github.com/mirage335/ubiquitous_bash

**Comment by oxr463** [comment]
@alkino, please test again. PR #130 has been merged in https://github.com/proot-me/PRoot/commit/28c4401e86e4c3a9e6a7b26c2707fe6519d45a37

**Comment by kpjensen** [comment]
I see the same error with kernel 4.15 when building proot from master.
I compiled from the forked udocker proot https://github.com/jorge-lip/PRoot/tree/udocker-1.1.1 and it executes okay and shows `proot info: ptrace acceleration (seccomp mode 2) enabled` in the debug log.

**Comment by oxr463** [comment]
Interesting, seeing as the fix in that fork, (See: https://github.com/jorge-lip/PRoot/commit/10ca3e88dc1d2e2b45439b181a168af6b4053b91), and this fix, (See: https://github.com/proot-me/PRoot/pull/130), were both authored by the same individual.. Can you post any relevant output/logs?

**Comment by kpjensen** [comment]
That's what didn't make sense to me given that it's the same patch.
Output from master after `make proot.static`
```
kjensen@kdev:~/PRoot/src$ cat /proc/version
Linux version 4.15.0-1033-aws (buildd@lgw01-amd64-037) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #35~16.04.1-Ubuntu SMP Thu Feb 14 15:58:01 UTC 2019
kjensen@kdev:~/PRoot/src$ git rev-parse HEAD
6694d34c83c2b6f2d47686bbe70e828580df9b56
kjensen@kdev:~/PRoot/src$ ./proot.static -v 9 ls
proot info: binding = /
proot info: vpid 1: translate("/home/kjensen/PRoot/src" + "ls")
proot info: vpid 1:          -> "/home/kjensen/PRoot/src/ls"
proot info: vpid 1: translate("/" + "/usr/local/sbin/ls")
proot info: vpid 1:          -> "/usr/local/sbin/ls"
proot info: vpid 1: translate("/" + "/usr/local/bin/ls")
proot info: vpid 1:          -> "/usr/local/bin/ls"
proot info: vpid 1: translate("/" + "/usr/sbin/ls")
proot info: vpid 1:          -> "/usr/sbin/ls"
proot info: vpid 1: translate("/" + "/usr/bin/ls")
proot info: vpid 1:          -> "/usr/bin/ls"
proot info: vpid 1: translate("/" + "/sbin/ls")
proot info: vpid 1:          -> "/sbin/ls"
proot info: vpid 1: translate("/" + "/bin/ls")
proot info: vpid 1:          -> "/bin/ls"
proot info: vpid 1: translate("/" + "/bin/ls")
proot info: vpid 1:          -> "/bin/ls"
proot info: exe = /bin/ls
proot info: argv = ls
proot info: initial cwd = /home/kjensen/PRoot/src
proot info: verbose level = 9
proot info: pid 10933: access to "/dev/pts/1" (fd 0) won't be translated until closed
proot info: pid 10933: access to "/dev/pts/1" (fd 1) won't be translated until closed
proot info: pid 10933: access to "/dev/pts/1" (fd 2) won't be translated until closed
proot info: pid 10933: access to "/proc/10933/fd" (fd 3) won't be translated until closed
proot info: vpid 1: sysenter start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x2758420) = 0xffffffffffffffda [0x7ffcc2412fb8, 0]
proot info: vpid 1: sysenter end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x2758420) = 0xffffffffffffffda [0x7ffcc2412fb8, 0]
proot info: vpid 1: sysexit start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x2758420) = 0x0 [0x7ffcc2412fb8, 0]
proot info: vpid 1: sysexit end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x2758420) = 0x0 [0x7ffcc2412fb8, 0]
proot info: vpid 1: sysenter start: prctl(0x16, 0x2, 0x7ffcc2413000, 0x477e1a, 0x0, 0x2758420) = 0xffffffffffffffda [0x7ffcc2412fb8, 0]
proot info: vpid 1: sysenter end: prctl(0x16, 0x2, 0x7ffcc2413000, 0x477e1a, 0x0, 0x2758420) = 0xffffffffffffffda [0x7ffcc2412fb8, 0]
proot info: vpid 1: sysexit start: prctl(0x16, 0x2, 0x7ffcc2413000, 0x477e1a, 0x0, 0x2758420) = 0x0 [0x7ffcc2412fb8, 0]
proot info: vpid 1: sysexit end: prctl(0x16, 0x2, 0x7ffcc2413000, 0x477e1a, 0x0, 0x2758420) = 0x0 [0x7ffcc2412fb8, 0]
proot info: vpid 1: sysenter start: execve(0x26ccf90, 0x7ffcc24132e0, 0x7ffcc24132f0, 0x477e1a, 0x0, 0x1) = 0xffffffffffffffda [0x7ffcc2413048, 0]
proot info: vpid 1: translate("/" + "/bin/ls")
proot info: vpid 1:          -> "/bin/ls"
proot info: vpid 1: translate("/" + "/lib64/ld-linux-x86-64.so.2")
proot info: vpid 1:          -> "/lib/x86_64-linux-gnu/ld-2.23.so"
proot info: loader: /tmp/prooted-10933-15WqP6
proot info: vpid 1: sysenter end: execve(0x7ffcc2412fae, 0x7ffcc24132e0, 0x7ffcc24132f0, 0x477e1a, 0x0, 0x1) = 0xffffffffffffffda [0x7ffcc2412fae, 0]
proot info: ptrace acceleration (seccomp mode 2) enabled
proot info: vpid 1: translate("/" + "/bin/ls")
proot info: vpid 1:          -> "/bin/ls"
proot info: vpid 1: terminated with signal 11
```
Output from the forked repo on the same machine.
```
kjensen@kdev:~/jorge/PRoot/src$ ./proot -v 9 ls
proot info: binding = /
proot info: vpid 1: translate("/home/kjensen/jorge/PRoot/src" + "ls")
proot info: vpid 1:          -> "/home/kjensen/jorge/PRoot/src/ls"
proot info: vpid 1: translate("/" + "/usr/local/sbin/ls")
proot info: vpid 1:          -> "/usr/local/sbin/ls"
proot info: vpid 1: translate("/" + "/usr/local/bin/ls")
proot info: vpid 1:          -> "/usr/local/bin/ls"
proot info: vpid 1: translate("/" + "/usr/sbin/ls")
proot info: vpid 1:          -> "/usr/sbin/ls"
proot info: vpid 1: translate("/" + "/usr/bin/ls")
proot info: vpid 1:          -> "/usr/bin/ls"
proot info: vpid 1: translate("/" + "/sbin/ls")
proot info: vpid 1:          -> "/sbin/ls"
proot info: vpid 1: translate("/" + "/bin/ls")
proot info: vpid 1:          -> "/bin/ls"
proot info: vpid 1: translate("/" + "/bin/ls")
proot info: vpid 1:          -> "/bin/ls"
proot info: exe = /bin/ls
proot info: argv = ls
proot info: initial cwd = /home/kjensen/jorge/PRoot/src
proot info: verbose level = 9
proot info: pid 11002: access to "/dev/pts/1" (fd 0) won't be translated until closed
proot info: pid 11002: access to "/dev/pts/1" (fd 1) won't be translated until closed
proot info: pid 11002: access to "/dev/pts/1" (fd 2) won't be translated until closed
proot info: pid 11002: access to "/proc/11002/fd" (fd 3) won't be translated until closed
proot info: ptrace acceleration (seccomp mode 2) enabled
proot info: vpid 1: sysenter start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x6e291f10) = 0xffffffffffffffda [0x7ffd59567038, 0]
proot info: vpid 1: sysenter end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x6e291f10) = 0xffffffffffffffda [0x7ffd59567038, 0]
proot info: vpid 1: sysexit start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x6e291f10) = 0x0 [0x7ffd59567038, 0]
proot info: vpid 1: sysexit end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x6e291f10) = 0x0 [0x7ffd59567038, 0]
proot info: vpid 1: sysenter start: execve(0xe88f90, 0x7ffd59567360, 0x7ffd59567370, 0x90a718, 0x0, 0x0) = 0xffffffffffffffda [0x7ffd595670c8, 0]
proot info: vpid 1: translate("/" + "/bin/ls")
proot info: vpid 1:          -> "/bin/ls"
proot info: vpid 1: translate("/" + "/lib64/ld-linux-x86-64.so.2")
proot info: vpid 1:          -> "/lib/x86_64-linux-gnu/ld-2.23.so"
proot info: loader: /tmp/prooted-11002-GmVLdK
proot info: vpid 1: sysenter end: execve(0x7ffd5956702e, 0x7ffd59567360, 0x7ffd59567370, 0x90a718, 0x0, 0x0) = 0xffffffffffffffda [0x7ffd5956702e, 0]
proot info: vpid 1: sysexit start: execve(0x0, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x0 [0x7ffd071ac040, 0]
proot info: vpid 1: sysexit end: execve(0x7ffd071abe98, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x0 [0x7ffd071abe98, 0]
proot info: vpid 1: sysenter start: open(0x7ffd071ac018, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xffffffffffffffda [0x7ffd071abe70, 0]
proot info: vpid 1: translate("/" + "/bin/ls")
proot info: vpid 1:          -> "/bin/ls"
proot info: vpid 1: sysenter end: open(0x7ffd071abde8, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xffffffffffffffda [0x7ffd071abe70, 0]
proot info: vpid 1: sysenter start: open(0x7ffd071ac020, 0x0, 0x0, 0x32, 0xffffffffffffffff, 0x0) = 0xffffffffffffffda [0x7ffd071abe70, 0]
proot info: vpid 1: translate("/" + "/lib64/ld-linux-x86-64.so.2")
proot info: vpid 1:          -> "/lib/x86_64-linux-gnu/ld-2.23.so"
proot info: vpid 1: sysenter end: open(0x7ffd071abdcf, 0x0, 0x0, 0x32, 0xffffffffffffffff, 0x0) = 0xffffffffffffffda [0x7ffd071abe70, 0]
proot info: vpid 1: sysenter start: brk(0x0, 0x4049a0, 0x7ffd071ac208, 0x1, 0x1, 0x7ffd071ac229) = 0xffffffffffffffda [0x7ffd071abf48, 0]
proot info: vpid 1: sysenter end: mmap(0x620000, 0x1000, 0x3, 0x22, 0xffffffffffffffff, 0x0) = 0xffffffffffffffda [0x7ffd071abf48, 0]
proot info: vpid 1: sysexit start: mmap(0x620000, 0x1000, 0x3, 0x22, 0xffffffffffffffff, 0x0) = 0x620000 [0x7ffd071abf48, 0]
proot info: vpid 1: sysexit end: brk(0x0, 0x4049a0, 0x7ffd071ac208, 0x1, 0x1, 0x7ffd071ac229) = 0x621000 [0x7ffd071abf48, 0]
proot info: vpid 1: sysenter start: access(0x6f000001fdc4, 0x0, 0x6f0000225e28, 0x10, 0x7ffd071f97b0, 0x7ffd071f9040) = 0xffffffffffffffda [0x7ffd071abd38, 0]
proot info: vpid 1: translate("/" + "/etc/ld.so.nohwcap")
proot info: vpid 1:          -> "/etc/ld.so.nohwcap"
proot info: vpid 1: sysenter end: access(0x7ffd071abca5, 0x0, 0x6f0000225e28, 0x10, 0x7ffd071f97b0, 0x7ffd071f9040) = 0xffffffffffffffda [0x7ffd071abd38, 0]
proot info: vpid 1: sysenter start: access(0x6f0000022580, 0x4, 0x0, 0x10, 0x2, 0x6f0000227ba8) = 0xffffffffffffffda [0x7ffd071abe58, 0]
proot info: vpid 1: translate("/" + "/etc/ld.so.preload")
proot info: vpid 1:          -> "/etc/ld.so.preload"
proot info: vpid 1: sysenter end: access(0x7ffd071abdc5, 0x4, 0x0, 0x10, 0x2, 0x6f0000227ba8) = 0xffffffffffffffda [0x7ffd071abe58, 0]
proot info: vpid 1: sysenter start: open(0x6f0000020271, 0x80000, 0x1, 0x6f0000227480, 0x0, 0x0) = 0xffffffffffffffda [0x7ffd071ab658, 0]
proot info: vpid 1: translate("/" + "/etc/ld.so.cache")
proot info: vpid 1:          -> "/etc/ld.so.cache"
proot info: vpid 1: sysenter end: open(0x7ffd071ab5c7, 0x80000, 0x1, 0x6f0000227480, 0x0, 0x0) = 0xffffffffffffffda [0x7ffd071ab658, 0]
proot info: vpid 1: sysenter start: access(0x6f000001fdc4, 0x0, 0x0, 0x10, 0x3, 0x0) = 0xffffffffffffffda [0x7ffd071ab718, 0]
proot info: vpid 1: translate("/" + "/etc/ld.so.nohwcap")
proot info: vpid 1:          -> "/etc/ld.so.nohwcap"
proot info: vpid 1: sysenter end: access(0x7ffd071ab685, 0x0, 0x0, 0x10, 0x3, 0x0) = 0xffffffffffffffda [0x7ffd071ab718, 0]
proot info: vpid 1: sysenter start: open(0x6f0000227d60, 0x80000, 0x6f0000227168, 0x78756e696c657362, 0x0, 0x7ffd071ab7ff) = 0xffffffffffffffda [0x7ffd071ab728, 0]
proot info: vpid 1: translate("/" + "/lib/x86_64-linux-gnu/libselinux.so.1")
proot info: vpid 1:          -> "/lib/x86_64-linux-gnu/libselinux.so.1"
proot info: vpid 1: sysenter end: open(0x7ffd071ab682, 0x80000, 0x6f0000227168, 0x78756e696c657362, 0x0, 0x7ffd071ab7ff) = 0xffffffffffffffda [0x7ffd071ab728, 0]
proot info: vpid 1: sysenter start: access(0x6f000001fdc4, 0x0, 0x200, 0x6f0000227480, 0xffff, 0x0) = 0xffffffffffffffda [0x7ffd071ab6e8, 0]
proot info: vpid 1: translate("/" + "/etc/ld.so.nohwcap")
proot info: vpid 1:          -> "/etc/ld.so.nohwcap"
proot info: vpid 1: sysenter end: access(0x7ffd071ab655, 0x0, 0x200, 0x6f0000227480, 0xffff, 0x0) = 0xffffffffffffffda [0x7ffd071ab6e8, 0]
proot info: vpid 1: sysenter start: open(0x7fef4463d4c8, 0x80000, 0x6f0000227168, 0x362e6f732e6362, 0x0, 0x7ffd071ab7cf) = 0xffffffffffffffda [0x7ffd071ab6f8, 0]
proot info: vpid 1: translate("/" + "/lib/x86_64-linux-gnu/libc.so.6")
proot info: vpid 1:          -> "/lib/x86_64-linux-gnu/libc-2.23.so"
proot info: vpid 1: sysenter end: open(0x7ffd071ab655, 0x80000, 0x6f0000227168, 0x362e6f732e6362, 0x0, 0x7ffd071ab7cf) = 0xffffffffffffffda [0x7ffd071ab6f8, 0]
proot info: vpid 1: sysenter start: access(0x6f000001fdc4, 0x0, 0x1000, 0x6f0000227480, 0x0, 0x0) = 0xffffffffffffffda [0x7ffd071ab5a8, 0]
proot info: vpid 1: translate("/" + "/etc/ld.so.nohwcap")
proot info: vpid 1:          -> "/etc/ld.so.nohwcap"
proot info: vpid 1: sysenter end: access(0x7ffd071ab515, 0x0, 0x1000, 0x6f0000227480, 0x0, 0x0) = 0xffffffffffffffda [0x7ffd071ab5a8, 0]
proot info: vpid 1: sysenter start: open(0x7fef4463d9a8, 0x80000, 0x7fef4463d000, 0x6f732e6572637062, 0x0, 0x7ffd071ab68f) = 0xffffffffffffffda [0x7ffd071ab5b8, 0]
proot info: vpid 1: translate("/" + "/lib/x86_64-linux-gnu/libpcre.so.3")
proot info: vpid 1:          -> "/lib/x86_64-linux-gnu/libpcre.so.3.13.2"
proot info: vpid 1: sysenter end: open(0x7ffd071ab510, 0x80000, 0x7fef4463d000, 0x6f732e6572637062, 0x0, 0x7ffd071ab68f) = 0xffffffffffffffda [0x7ffd071ab5b8, 0]
proot info: vpid 1: sysenter start: access(0x6f000001fdc4, 0x0, 0x400, 0x6f0000227480, 0xffff, 0x0) = 0xffffffffffffffda [0x7ffd071ab578, 0]
proot info: vpid 1: translate("/" + "/etc/ld.so.nohwcap")
proot info: vpid 1:          -> "/etc/ld.so.nohwcap"
proot info: vpid 1: sysenter end: access(0x7ffd071ab4e5, 0x0, 0x400, 0x6f0000227480, 0xffff, 0x0) = 0xffffffffffffffda [0x7ffd071ab578, 0]
proot info: vpid 1: sysenter start: open(0x7fef4463de98, 0x80000, 0x7fef4463d000, 0x322e6f732e6c6462, 0x0, 0x7ffd071ab65f) = 0xffffffffffffffda [0x7ffd071ab588, 0]
proot info: vpid 1: translate("/" + "/lib/x86_64-linux-gnu/libdl.so.2")
proot info: vpid 1:          -> "/lib/x86_64-linux-gnu/libdl-2.23.so"
proot info: vpid 1: sysenter end: open(0x7ffd071ab4e4, 0x80000, 0x7fef4463d000, 0x322e6f732e6c6462, 0x0, 0x7ffd071ab65f) = 0xffffffffffffffda [0x7ffd071ab588, 0]
proot info: vpid 1: sysenter start: access(0x6f000001fdc4, 0x0, 0x8000, 0x6f0000227480, 0xffff, 0x0) = 0xffffffffffffffda [0x7ffd071ab518, 0]
proot info: vpid 1: translate("/" + "/etc/ld.so.nohwcap")
proot info: vpid 1:          -> "/etc/ld.so.nohwcap"
proot info: vpid 1: sysenter end: access(0x7ffd071ab485, 0x0, 0x8000, 0x6f0000227480, 0xffff, 0x0) = 0xffffffffffffffda [0x7ffd071ab518, 0]
proot info: vpid 1: sysenter start: open(0x7fef43de0548, 0x80000, 0x7fef4463d9d0, 0x6461657268747062, 0x0, 0x7ffd071ab5ff) = 0xffffffffffffffda [0x7ffd071ab528, 0]
proot info: vpid 1: translate("/" + "/lib/x86_64-linux-gnu/libpthread.so.0")
proot info: vpid 1:          -> "/lib/x86_64-linux-gnu/libpthread-2.23.so"
proot info: vpid 1: sysenter end: open(0x7ffd071ab47f, 0x80000, 0x7fef4463d9d0, 0x6461657268747062, 0x0, 0x7ffd071ab5ff) = 0xffffffffffffffda [0x7ffd071ab528, 0]
proot info: vpid 1: sysenter start: statfs(0x7fef44433c31, 0x7ffd071abec0, 0xfffffffffff45142, 0x72d, 0x6f0000227d60, 0x2f) = 0xffffffffffffffda [0x7ffd071abe48, 0]
proot info: vpid 1: translate("/" + "/sys/fs/selinux")
proot info: vpid 1:          -> "/sys/fs/selinux"
proot info: vpid 1: sysenter end: statfs(0x7ffd071abdb8, 0x7ffd071abec0, 0xfffffffffff45142, 0x72d, 0x6f0000227d60, 0x2f) = 0xffffffffffffffda [0x7ffd071abe48, 0]
proot info: vpid 1: sysenter start: statfs(0x7fef44433c38, 0x7ffd071abec0, 0xfffffffffff45142, 0x370, 0x6f0000227d60, 0x2f) = 0xffffffffffffffda [0x7ffd071abe48, 0]
proot info: vpid 1: translate("/" + "/selinux")
proot info: vpid 1:          -> "/selinux"
proot info: vpid 1: sysenter end: statfs(0x7ffd071abdbf, 0x7ffd071abec0, 0xfffffffffff45142, 0x370, 0x6f0000227d60, 0x2f) = 0xffffffffffffffda [0x7ffd071abe48, 0]
proot info: vpid 1: sysenter start: brk(0x0, 0x7fef44415b20, 0x7fef44415b78, 0x7fef44415b78, 0x0, 0xd) = 0xffffffffffffffda [0x7ffd071abd08, 0]
proot info: vpid 1: sysenter end: void(0x0, 0x7fef44415b20, 0x7fef44415b78, 0x7fef44415b78, 0x0, 0xd) = 0xffffffffffffffda [0x7ffd071abd08, 0]
proot info: vpid 1: sysexit start: void(0x0, 0x7fef44415b20, 0x7fef44415b78, 0x7fef44415b78, 0x0, 0xd) = 0xffffffffffffffda [0x7ffd071abd08, 0]
proot info: vpid 1: sysexit end: brk(0x0, 0x7fef44415b20, 0x7fef44415b78, 0x7fef44415b78, 0x0, 0xd) = 0x621000 [0x7ffd071abd08, 0]
proot info: vpid 1: sysenter start: brk(0x642000, 0x7fef44415b20, 0x621000, 0x7fef44415b78, 0x0, 0xd) = 0xffffffffffffffda [0x7ffd071abd08, 0]
proot info: vpid 1: sysenter end: mremap(0x620000, 0x1000, 0x22000, 0x0, 0x0, 0xd) = 0xffffffffffffffda [0x7ffd071abd08, 0]
proot info: vpid 1: sysexit start: mremap(0x620000, 0x1000, 0x22000, 0x0, 0x0, 0xd) = 0x620000 [0x7ffd071abd08, 0]
proot info: vpid 1: sysexit end: brk(0x642000, 0x7fef44415b20, 0x621000, 0x7fef44415b78, 0x0, 0xd) = 0x642000 [0x7ffd071abd08, 0]
proot info: vpid 1: sysenter start: open(0x7fef44433c15, 0x0, 0x1b6, 0x0, 0x8, 0x1) = 0xffffffffffffffda [0x7ffd071abe48, 0]
proot info: vpid 1: translate("/" + "/proc/filesystems")
proot info: vpid 1:          -> "/proc/filesystems"
proot info: vpid 1: sysenter end: open(0x7ffd071abdb6, 0x0, 0x1b6, 0x0, 0x8, 0x1) = 0xffffffffffffffda [0x7ffd071abe48, 0]
proot info: vpid 1: sysenter start: open(0x7fef441e4760, 0x80000, 0x0, 0x7fef440ddbf0, 0x621010, 0x0) = 0xffffffffffffffda [0x7ffd071ab870, 0]
proot info: vpid 1: translate("/" + "/usr/lib/locale/locale-archive")
proot info: vpid 1:          -> "/usr/lib/locale/locale-archive"
proot info: vpid 1: sysenter end: open(0x7ffd071ab7d1, 0x80000, 0x0, 0x7fef440ddbf0, 0x621010, 0x0) = 0xffffffffffffffda [0x7ffd071ab870, 0]
proot info: vpid 1: sysenter start: open(0x626c80, 0x90800, 0x2, 0x502, 0x7ffd071abbe0, 0x0) = 0xffffffffffffffda [0x7ffd071abb00, 0]
proot info: vpid 1: translate("/home/kjensen/jorge/PRoot/src" + ".")
proot info: vpid 1:          -> "/home/kjensen/jorge/PRoot/src/."
proot info: vpid 1: sysenter end: open(0x7ffd071aba60, 0x90800, 0x2, 0x502, 0x7ffd071abbe0, 0x0) = 0xffffffffffffffda [0x7ffd071abb00, 0]
arch.h	attribute.h  build.h  cli  compat.h  execve  extension	GNUmakefile  loader  path  proot  ptrace  syscall  tracee
proot info: vpid 1: exited with status 0
```

**Comment by oxr463** [comment]
I'll dig into this. Thanks for the input!

**Comment by oxr463** [comment]
Immediately one big difference that comes to mind is, the fix committed here is using pre-processor logic, i.e., macros, which is executed at compile time, whereas the fork uses logic at runtime to determine the host kernel version.

Your log output shows kernel version 4.15 so I'm puzzled as to why it is falling.

**Comment by oxr463** [comment]
@kpjensen, can you test on this branch, (https://github.com/proot-me/PRoot/tree/fix-seccomp)?

**Comment by vityafx** [comment]
Hi guys. I had sort of similar problem with `ptrace`. In my case, children and sub-children were crashing because of, I think, not checking the result of their `fork()` and something else (a bug, actually). I've found that this problem occurs only with binaries which have subprocesses or multiple threads, so I decided to dig deeper into that. I've found that the tracer was not set by the kernel to the child processes and that, actually, every system call unlisted in my `seccomp` rules was returning `-ENOSYS`, but even when I specified it, others returned ENOSYS and so this lead to a crash. As I did not want to specify all of them and handle all the cases (my debugger really needed to trace only a few system calls), I needed another solution. The solution was to become a tracer of sub-children as well (and actually I also needed that).

I haven't looked much at your code (not at all, actually), but if you have something similar to that, you may look at my problem and solution more detailed on the [stackoverflow](https://stackoverflow.com/questions/56024498/cant-trace-a-subprocesss-syscalls-which-calls-execve-using-ptrace-and-seccomp).

**Comment by oxr463** [comment]
```
In file included from /usr/include/stdio.h:27:0,
                 from exec.c:1:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
```

Source: https://travis-ci.org/proot-me/proot/builds/532081135#L727

**Comment by oxr463** [comment]
Posted on stackoverflow, (See: https://stackoverflow.com/questions/56535083/how-to-fix-segsegv-with-recent-kernel-and-seccomp).

**Comment by Kilo-411** [comment]
$ export PROOT_NO_SECCOMP=1
$ ./start-debian.sh
bash: xmalloc: .././shell.c:1709: cannot allocate 10 bytes (0 bytes allocated)
$ ./start-debian.sh
bash: xmalloc: .././shell.c:1709: cannot allocate 10 bytes (0 bytes allocated)
$
 I have no dir for the com.termux but I know I do
orginal code 
$ ./start-debian.sh
proot info: vpid 1: terminated with signal 11

of course. been an issue every since I had to hardreset my lg premier pro lm x410fg phone

**Comment by sr229** [comment]
Hey proot devs, if this helps, looks like Debian's version of `proot` works on 4.x kernels, worth looking for their patches?

**Comment by sr229** [comment]
Hey proot devs, if this helps, looks like Debian's version of `proot` works on 4.x kernels, worth looking for their patches?

**Comment by oxr463** [comment]
http://man7.org/linux/man-pages/man2/seccomp.2.html

**Comment by katakombi** [comment]
No idea if that will be helpful, but just fyi:
https://www.phoronix.com/scan.php?page=news_item&px=Linux-Syscall-Isolate-Memory

**Comment by mboisson** [comment]
Hi. This happens with the newest CentOS7 kernel. 

```
[mboisson@build-node2 ~]$ proot --version
 _____ _____              ___
|  __ \  __ \_____  _____|   |_
|   __/     /  _  \/  _  \    _|
|__|  |__|__\_____/\_____/\____| 5.1.0

built-in accelerators: process_vm = yes, seccomp_filter = yes

Visit http://proot.me for help, bug reports, suggestions, patchs, ...
Copyright (C) 2014 STMicroelectronics, licensed under GPL v2 or later.
[mboisson@build-node2 ~]$ uname -r
3.10.0-1127.13.1.el7.x86_64
```

**Comment by katakombi** [comment]
> Hi. This happens with the newest CentOS7 kernel.
> 
> ```
> [mboisson@build-node2 ~]$ proot --version
>  _____ _____              ___
> |  __ \  __ \_____  _____|   |_
> |   __/     /  _  \/  _  \    _|
> |__|  |__|__\_____/\_____/\____| 5.1.0
> 
> built-in accelerators: process_vm = yes, seccomp_filter = yes
> 
> Visit http://proot.me for help, bug reports, suggestions, patchs, ...
> Copyright (C) 2014 STMicroelectronics, licensed under GPL v2 or later.
> [mboisson@build-node2 ~]$ /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/bin/proot -b /tmp:/home/mboisson/tmp bash -l
> proot info: pid 3431: terminated with signal 11
> [mboisson@build-node2 ~]$ uname -r
> 3.10.0-1127.13.1.el7.x86_64
> ```

Hi @mboisson can you also try the recently released 5.2.0 alpha version? It solved many issues for me, however, I am running newer kernel versions.

**Comment by Apteryks** [comment]
Seems to be OK on latest commit.

**Comment by oxr463** [comment]
Agreed! I'm going to close this FINALLY!

**Comment by yuyichao** [comment]
Note that on my system (archlinux x64, armv7h and aarch64) I’m still seeing a few failures related to seccomp. In particular, the execve issued by the loader doesn’t get picked up by the enter handler and actually get sent to the kernel which resulted in a memory access error and abort of the tracee. Disabling seccomp get rid of that issue…
